### ISSUE TITLE
从1946年9月30号往前的日子，新历转农历的getDayInChinese都是返回错误

### ISSUE THREAD

**Issue by caoyanglee** [6tail/lunar-java#10]
1946年9月30号 => 九月初五，实际上是九月初六才对。往前的日子都一样，按农历来算都是少一天！

版本:[v1.2.5]

**Comment by 6tail** [comment]
能附上调用代码吗？我测试1946年9月30日是九月初六，没有你说的问题。

**Comment by caoyanglee** [comment]
最新版已经好了！
