### ISSUE TITLE
当节气间隔为16天时，物候算法异常以及疑问

### ISSUE THREAD

**Issue by bigbiglemon** [6tail/lunar-java#13]
版本: v1.2.18
语言: java
错误描述: 版本新增的物候，其中计算方式取两个节气相差天数除以5作为参数计算，但是节气之间相差天数可能>15天，比如2022年5月5日为“立夏”、2022年5月21为“小满”，两节气相差16天，导致5月20日结果计算异常
code eg:(5月20日）
lunar.getHou() == "立夏 初候“; 
lunar.getWuhou() == "苦菜秀";

疑问：现在第16天被算做”初候“，实际上如果超过15天的也算”三候“???

**Comment by 6tail** [comment]
v1.2.19 已修复。
