### ISSUE TITLE
lunar类的干支方法返回错误

### ISSUE THREAD

**Issue by swq93** [6tail/lunar-java#18]
java lunar对象get干支，结果错误，用eightchar没没问题。时间2022年4月6日20点18分。返回己丑，己丑，己丑，甲戌

**Comment by 6tail** [comment]
不知道你怎么调用的，测试没有问题。

  @Test
  public void test19() {
    Solar solar = new Solar(2022,4,6,20,18,0);
    Lunar lunar = solar.getLunar();
    Assert.assertEquals("壬寅",lunar.getYearInGanZhi());
    Assert.assertEquals("壬寅",lunar.getYearInGanZhiByLiChun());
    Assert.assertEquals("壬寅",lunar.getYearInGanZhiExact());

    Assert.assertEquals("甲辰",lunar.getMonthInGanZhi());
    Assert.assertEquals("甲辰",lunar.getMonthInGanZhiExact());

    Assert.assertEquals("己丑",lunar.getDayInGanZhi());
    Assert.assertEquals("己丑",lunar.getDayInGanZhiExact());
    Assert.assertEquals("己丑",lunar.getDayInGanZhiExact2());

    Assert.assertEquals("甲戌",lunar.getTimeInGanZhi());
  }
