### ISSUE TITLE
沒有檢查農歷大小月

### ISSUE THREAD

**Issue by Patrick-foreseers** [6tail/lunar-java#2]
貳零貳零年正月三十 庚子(鼠)年 戊寅(虎)月 丙申(猴)日 子(鼠)時 納音[壁上土 城頭土 山下火 海中金] 星期日 北方玄武 執星[破] 星宿[虛日鼠](凶) 彭祖百忌[丙不修灶必見災殃 申不安床鬼祟入房] 喜神方位[坤](西南) 陽貴神方位[兌](正西) 陰貴神方位[乾](西北) 福神方位[震](正東) 財神方位[坤](西南) 冲[(庚寅)虎] 煞[南]
2020-02-23 00:00:00 閏年 星期日 雙魚座
[庚子, 戊寅, 丙申, 戊子]
貳零貳零年貳月三十 庚子(鼠)年 己卯(兔)月 乙丑(牛)日 子(鼠)時 納音[壁上土 城頭土 海中金 海中金] 星期一 北方玄武 執星[開] 星宿[危月燕](凶) 彭祖百忌[乙不栽植千株不長 丑不冠帶主不還鄉] 喜神方位[乾](西北) 陽貴神方位[坤](西南) 陰貴神方位[坎](正北) 福神方位[巽](東南) 財神方位[艮](東北) 冲[(己未)羊] 煞[東]
2020-03-23 00:00:00 閏年 星期一 白羊座
[庚子, 己卯, 乙丑, 丙子]
貳零貳零年叁月三十 庚子(鼠)年 庚辰(龍)月 乙未(羊)日 子(鼠)時 納音[壁上土 白蠟金 沙中金 海中金] 星期三 北方玄武 執星[平] 星宿[壁水獝](吉) 彭祖百忌[乙不栽植千株不長 未不服藥毒氣入腸] 喜神方位[乾](西北) 陽貴神方位[坤](西南) 陰貴神方位[坎](正北) 福神方位[巽](東南) 財神方位[艮](東北) 冲[(己丑)牛] 煞[西]
2020-04-22 00:00:00 閏年 星期三 金牛座
[庚子, 庚辰, 乙未, 丙子]
貳零貳零年肆月三十 庚子(鼠)年 辛巳(蛇)月 乙丑(牛)日 子(鼠)時 納音[壁上土 白蠟金 海中金 海中金] 星期五 西方白虎 執星[成] 星宿[婁金狗](吉) 彭祖百忌[乙不栽植千株不長 丑不冠帶主不還鄉] 喜神方位[乾](西北) 陽貴神方位[坤](西南) 陰貴神方位[坎](正北) 福神方位[巽](東南) 財神方位[艮](東北) 冲[(己未)羊] 煞[東]
2020-05-22 00:00:00 閏年 星期五 雙子座
[庚子, 辛巳, 乙丑, 丙子]
貳零貳零年伍月三十 庚子(鼠)年 癸未(羊)月 甲子(鼠)日 子(鼠)時 納音[壁上土 楊柳木 海中金 海中金] 星期一 西方白虎 執星[執] 星宿[畢月烏](吉) 彭祖百忌[甲不開倉財物耗散 子不問卜自惹禍殃] 喜神方位[艮](東北) 陽貴神方位[坤](西南) 陰貴神方位[艮](東北) 福神方位[巽](東南) 財神方位[艮](東北) 冲[(戊午)馬] 煞[南]
2020-07-20 00:00:00 閏年 星期一 巨蟹座
[庚子, 癸未, 甲子, 甲子]
貳零貳零年陸月三十 庚子(鼠)年 甲申(猴)月 甲午(馬)日 子(鼠)時 納音[壁上土 泉中水 沙中金 海中金] 星期三 西方白虎 執星[開] 星宿[參水猿](吉) 彭祖百忌[甲不開倉財物耗散 午不苫蓋屋主更張] 喜神方位[艮](東北) 陽貴神方位[坤](西南) 陰貴神方位[艮](東北) 福神方位[巽](東南) 財神方位[艮](東北) 冲[(戊子)鼠] 煞[北]
2020-08-19 00:00:00 閏年 星期三 獅子座
[庚子, 甲申, 甲午, 甲子]
貳零貳零年柒月三十 庚子(鼠)年 乙酉(雞)月 癸亥(豬)日 子(鼠)時 納音[壁上土 泉中水 大海水 海中金] 星期四 南方朱雀 執星[滿] 星宿[井木犴](吉) 彭祖百忌[癸不詞訟理弱敵強 亥不嫁娶不利新郎] 喜神方位[巽](東南) 陽貴神方位[巽](東南) 陰貴神方位[震](正東) 福神方位[兌](正西) 財神方位[離](正南) 冲[(丁巳)蛇] 煞[西]
2020-09-17 00:00:00 閏年 星期四 處女座
[庚子, 乙酉, 癸亥, 壬子]
貳零貳零年捌月三十 庚子(鼠)年 丙戌(狗)月 壬辰(龍)日 子(鼠)時 納音[壁上土 屋上土 長流水 海中金] 星期五 南方朱雀 執星[破] 星宿[鬼金羊](凶) 彭祖百忌[壬不泱水更難提防 辰不哭泣必主重喪] 喜神方位[離](正南) 陽貴神方位[震](正東) 陰貴神方位[巽](東南) 福神方位[乾](西北) 財神方位[離](正南) 冲[(丙戌)狗] 煞[南]
2020-10-16 00:00:00 閏年 星期五 天秤座
[庚子, 丙戌, 壬辰, 庚子]
貳零貳零年玖月三十 庚子(鼠)年 丁亥(豬)月 壬戌(狗)日 子(鼠)時 納音[壁上土 屋上土 大海水 海中金] 星期日 南方朱雀 執星[閉] 星宿[星日馬](凶) 彭祖百忌[壬不泱水更難提防 戌不吃犬作怪上床] 喜神方位[離](正南) 陽貴神方位[震](正東) 陰貴神方位[巽](東南) 福神方位[乾](西北) 財神方位[離](正南) 冲[(丙辰)龍] 煞[北]
2020-11-15 00:00:00 閏年 星期日 天蠍座
[庚子, 丁亥, 壬戌, 庚子]
貳零貳零年拾月三十 庚子(鼠)年 戊子(鼠)月 辛卯(兔)日 子(鼠)時 納音[壁上土 霹靂火 松柏木 海中金] 星期一 南方朱雀 執星[平] 星宿[張月鹿](吉) 彭祖百忌[辛不合醬主人不嘗 卯不穿井水泉不香] 喜神方位[坤](西南) 陽貴神方位[艮](東北) 陰貴神方位[離](正南) 福神方位[坤](西南) 財神方位[震](正東) 冲[(乙酉)雞] 煞[西]
2020-12-14 00:00:00 閏年 星期一 射手座
[庚子, 戊子, 辛卯, 戊子]
貳零貳零年冬月三十 庚子(鼠)年 己丑(牛)月 辛酉(雞)日 子(鼠)時 納音[壁上土 霹靂火 石榴木 海中金] 星期三 南方朱雀 執星[成] 星宿[軫水蚓](吉) 彭祖百忌[辛不合醬主人不嘗 酉不會客醉坐顛狂] 喜神方位[坤](西南) 陽貴神方位[艮](東北) 陰貴神方位[離](正南) 福神方位[坤](西南) 財神方位[震](正東) 冲[(乙卯)兔] 煞[東]
2021-01-13 00:00:00 星期三 摩羯座
[庚子, 己丑, 辛酉, 戊子]
貳零貳零年臘月三十 庚子(鼠)年 戊寅(虎)月 庚寅(虎)日 子(鼠)時 納音[壁上土 城頭土 松柏木 海中金] 星期四 (除夕) 東方青龍 執星[建] 星宿[角木蛟](吉) 彭祖百忌[庚不經絡織機虛張 寅不祭祀神鬼不嘗] 喜神方位[乾](西北) 陽貴神方位[離](正南) 陰貴神方位[艮](東北) 福神方位[坤](西南) 財神方位[震](正東) 冲[(甲申)猴] 煞[北]
2021-02-11 00:00:00 星期四 水瓶座
[庚子, 戊寅, 庚寅, 丙子]

**Comment by 6tail** [comment]
农历大小月可以通过这个方法（获取农历年月的天数）判断：
LunarUtil.getDaysOfMonth(year, month)
大月30天，小月29天
传入农历年和农历月（闰月为负数，例如-3代表闰3月）

**Comment by 6tail** [comment]
已增加阴历初始化时月和日的校验。

**Comment by Patrick-foreseers** [comment]
成功了，謝謝。
