### ISSUE TITLE
您好，有支持时辰宜忌、吉神宜趋和凶神宜趋么

### ISSUE THREAD

**Issue by tiamosu** [6tail/lunar-java#3]

**Comment by 6tail** [comment]
我也想做，但是找了很久，没找到相关的资料，如果你有，可以提供一下。

**Comment by tiamosu** [comment]
> 我也想做，但是找了很久，没找到相关的资料，如果你有，可以提供一下。

我这边有份资料  您可以看下是否可行
[万年历_files.zip](https://github.com/6tail/lunar-java/files/4676774/_files.zip)

**Comment by 6tail** [comment]
> > 我也想做，但是找了很久，没找到相关的资料，如果你有，可以提供一下。
> 
> 我这边有份资料 您可以看下是否可行
> [万年历_files.zip](https://github.com/6tail/lunar-java/files/4676774/_files.zip)

这个代码我之前看过，粗看宜忌数据跟百度万年历的结果相差较大所以没有采用。

**Comment by 6tail** [comment]
@tiamosu 我已经想到办法新增支持了每日宜忌，时辰宜忌、吉神宜趋等后续也会增加支持。

**Comment by tiamosu** [comment]
> @tiamosu 我已经想到办法新增支持了每日宜忌，时辰宜忌、吉神宜趋等后续也会增加支持。

**Comment by tiamosu** [comment]
> > @tiamosu 我已经想到办法新增支持了每日宜忌，时辰宜忌、吉神宜趋等后续也会增加支持。
> 
> 厉害୧(๑•̀◡•́๑)૭

刚好做项目用到这个  非常感谢~
还差一个时辰宜忌就全了 哈哈

**Comment by 6tail** [comment]
@tiamosu 已新增时辰宜忌。

**Comment by tiamosu** [comment]
> @tiamosu 已新增时辰宜忌。

赞~

还有个问题，后续会支持时辰吉凶吗

**Comment by 6tail** [comment]
> > @tiamosu 已新增时辰宜忌。
> 
> 赞~
> 
> 还有个问题，后续会支持时辰吉凶吗

必须的。

**Comment by 6tail** [comment]
@tiamosu 已新增时辰十二天神、时辰黑黄道、时辰吉凶；修复黑黄道吉凶错误。
