### ISSUE TITLE
您好，能支持下九星推算吗

### ISSUE THREAD

**Issue by ebolavirus** [6tail/lunar-java#4]

**Comment by ebolavirus** [comment]
月相的代码也可以参考添加下，挺简单 ：）
/** 月相 */
  public static final String[] YUE_XIANG= {"",
		  "新(朔)月","既朔月","娥眉新月","娥眉新月","娥眉月","夕月","上弦月","上弦月","九夜月","宵月",
		  "宵月","宵月","渐盈凸月","小望月","满(望)月","既望月","立待月","居待月","寝待月","更待月",
		  "渐亏凸月","下弦月","下弦月","有明月","有明月","娥眉残月","娥眉残月","残月","晓月","晦月","有明月","有明月","有明月","有明月","有明月"};

**Comment by 6tail** [comment]
> 月相的代码也可以参考添加下，挺简单 ：）
> /** 月相 */
> public static final String[] YUE_XIANG= {"",
> "新(朔)月","既朔月","娥眉新月","娥眉新月","娥眉月","夕月","上弦月","上弦月","九夜月","宵月",
> "宵月","宵月","渐盈凸月","小望月","满(望)月","既望月","立待月","居待月","寝待月","更待月",
> "渐亏凸月","下弦月","下弦月","有明月","有明月","娥眉残月","娥眉残月","残月","晓月","晦月","有明月","有明月","有明月","有明月","有明月"};

对应关系是怎样的？

**Comment by 6tail** [comment]
@ebolavirus 九星推算需要得到哪些数据？

**Comment by ebolavirus** [comment]
> > 月相的代码也可以参考添加下，挺简单 ：）
> > /** 月相 */
> > public static final String[] YUE_XIANG= {"",
> > "新(朔)月","既朔月","娥眉新月","娥眉新月","娥眉月","夕月","上弦月","上弦月","九夜月","宵月",
> > "宵月","宵月","渐盈凸月","小望月","满(望)月","既望月","立待月","居待月","寝待月","更待月",
> > "渐亏凸月","下弦月","下弦月","有明月","有明月","娥眉残月","娥眉残月","残月","晓月","晦月","有明月","有明月","有明月","有明月","有明月"};
> 
> 对应关系是怎样的？

按农历的“日”套上这个数组就行了，比如农历*月1号是新（朔）月，4号是“娥眉新月”

**Comment by ebolavirus** [comment]
九星就是按日取到当日的以下九星之一：
一白-太乙星(水)-吉神
二黒-摄提星(土)-凶神
三碧-轩辕星(木)-安神
四緑-招摇星(木)-安神
五黄-天符星(土)-凶神
六白-青龙星(金)-吉神
七赤-咸池星(金)-凶神
八白-太阴星(土)-吉神
九紫-天乙星(火)-吉神

**Comment by 6tail** [comment]
> > > 月相的代码也可以参考添加下，挺简单 ：）
> > > /** 月相 */
> > > public static final String[] YUE_XIANG= {"",
> > > "新(朔)月","既朔月","娥眉新月","娥眉新月","娥眉月","夕月","上弦月","上弦月","九夜月","宵月",
> > > "宵月","宵月","渐盈凸月","小望月","满(望)月","既望月","立待月","居待月","寝待月","更待月",
> > > "渐亏凸月","下弦月","下弦月","有明月","有明月","娥眉残月","娥眉残月","残月","晓月","晦月","有明月","有明月","有明月","有明月","有明月"};
> > 
> > 
> > 对应关系是怎样的？
> 
> 按农历的“日”套上这个数组就行了，比如农历*月1号是新（朔）月，4号是“娥眉新月”

后面多出的几个怎么处理？

**Comment by 6tail** [comment]
> 九星就是按日取到当日的以下九星之一：
> 一白-太乙星(水)-吉神
> 二黒-摄提星(土)-凶神
> 三碧-轩辕星(木)-安神
> 四緑-招摇星(木)-安神
> 五黄-天符星(土)-凶神
> 六白-青龙星(金)-吉神
> 七赤-咸池星(金)-凶神
> 八白-太阴星(土)-吉神
> 九紫-天乙星(火)-吉神

关于九星，我网上找了很多资料，九数、七色、五行还比较统一，一白水，二黑土等，但是关于名称，各个地方出处不同，叫法不同，更统一的为贪狼、巨门、禄存等名称，道教又对应九皇星君（太星君、元星君、真星君），然后又有叫天枢、天璇、天玑的，奇门遁甲里又称天蓬、天芮、天冲等。太乙、摄提、轩辕也能找到相关信息，但出处我没找到。感觉还需要时间理清楚头绪。

**Comment by 6tail** [comment]
@ebolavirus 增加支持了月相和值年九星。月、日、时的推算貌似比较复杂，还要等段时间。

**Comment by ebolavirus** [comment]
b(￣▽￣)ｄ 我手里有一套javascript版本的，不知道有没有帮助：https://gitee.com/xiaoluoli/Wannianli

**Comment by 6tail** [comment]
> b(￣▽￣)ｄ 我手里有一套javascript版本的，不知道有没有帮助：https://gitee.com/xiaoluoli/Wannianli

@ebolavirus 已支持值年、值月、值日、值时九星。

我参考这个文章实现的逻辑：http://www.360doc.com/content/18/0206/20/42343301_728211774.shtml，对比后感觉你提供那个js的结果是错的。
